version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    command: sleep infinity
    networks:
      - dev_network

  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "13307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_network

volumes:
  mysql_data:
    driver: local

networks:
  dev_network:
    driver: bridge
